INSERT INTO public.categorias (slug, rama_id, rama_nombre, grupo, nombre, actores, orden)
VALUES
('1.1.1', 1, '1. Extracción y recursos primarios', '1.1 Minería no metálica', 'Áridos (grava, arena y piedra picada)', '{F}', 1),
('1.1.2', 1, '1. Extracción y recursos primarios', '1.1 Minería no metálica', 'Rocas ornamentales (granito y mármol)', '{F}', 2),
('1.1.3', 1, '1. Extracción y recursos primarios', '1.1 Minería no metálica', 'Calizas y arcillas', '{F}', 3),
('1.2.1', 1, '1. Extracción y recursos primarios', '1.2 Minería metálica', 'Minerales de hierro, bauxita y cobre', '{F}', 4),
('1.3.1', 1, '1. Extracción y recursos primarios', '1.3 Otros recursos primarios', 'Madera cruda (sector forestal)', '{F}', 5),
('1.3.2', 1, '1. Extracción y recursos primarios', '1.3 Otros recursos primarios', 'Agua industrial', '{F}', 6),
('1.3.3', 1, '1. Extracción y recursos primarios', '1.3 Otros recursos primarios', 'Hidrocarburos y derivados de soporte', '{F}', 7),
('2.1.1', 2, '2. Manufactura de materiales', '2.1 Cemento, concreto y prefabricados', 'Cemento y clínker', '{F}', 8),
('2.1.2', 2, '2. Manufactura de materiales', '2.1 Cemento, concreto y prefabricados', 'Concreto premezclado y morteros', '{F}', 9),
('2.1.3', 2, '2. Manufactura de materiales', '2.1 Cemento, concreto y prefabricados', 'Cal y yeso', '{F}', 10),
('2.1.4', 2, '2. Manufactura de materiales', '2.1 Cemento, concreto y prefabricados', 'Bloques, adoquines y tubos de concreto', '{F}', 11),
('2.1.5', 2, '2. Manufactura de materiales', '2.1 Cemento, concreto y prefabricados', 'Vigas pretensadas y losacero', '{F}', 12),
('2.2.1', 2, '2. Manufactura de materiales', '2.2 Cerámica, vidrio y sistemas livianos', 'Ladrillos, tejas y arcilla', '{F}', 13),
('2.2.2', 2, '2. Manufactura de materiales', '2.2 Cerámica, vidrio y sistemas livianos', 'Baldosas y porcelanatos', '{F}', 14),
('2.2.3', 2, '2. Manufactura de materiales', '2.2 Cerámica, vidrio y sistemas livianos', 'Piezas sanitarias', '{F}', 15),
('2.2.4', 2, '2. Manufactura de materiales', '2.2 Cerámica, vidrio y sistemas livianos', 'Vidrio plano, templado y laminado', '{F}', 16),
('2.2.5', 2, '2. Manufactura de materiales', '2.2 Cerámica, vidrio y sistemas livianos', 'Drywall y fibrocemento', '{F}', 17),
('2.3.1', 2, '2. Manufactura de materiales', '2.3 Acero y metalurgia', 'Cabillas, mallas y estribos de refuerzo', '{F}', 18),
('2.3.2', 2, '2. Manufactura de materiales', '2.3 Acero y metalurgia', 'Perfiles y planchas estructurales', '{F}', 19),
('2.3.3', 2, '2. Manufactura de materiales', '2.3 Acero y metalurgia', 'Láminas de techo (galvanizadas, termoacústicas, zinc)', '{F}', 20),
('2.3.4', 2, '2. Manufactura de materiales', '2.3 Acero y metalurgia', 'Aluminio para ventanas y cerramientos', '{F}', 21),
('2.3.5', 2, '2. Manufactura de materiales', '2.3 Acero y metalurgia', 'Fabricación de clavos, tornillos y anclajes', '{F}', 22),
('2.4.1', 2, '2. Manufactura de materiales', '2.4 Plásticos y química', 'Tuberías PVC, CPVC, PEAD, PPR y tanques', '{F}', 23),
('2.4.2', 2, '2. Manufactura de materiales', '2.4 Plásticos y química', 'Fabricación de pinturas, masillas y anticorrosivos', '{F}', 24),
('2.4.3', 2, '2. Manufactura de materiales', '2.4 Plásticos y química', 'Impermeabilizantes, mantos asfálticos y selladores', '{F}', 25),
('2.4.4', 2, '2. Manufactura de materiales', '2.4 Plásticos y química', 'Aditivos para concreto, resinas y pegos', '{F}', 26),
('2.5.1', 2, '2. Manufactura de materiales', '2.5 Material eléctrico', 'Cables eléctricos (baja, media y alta tensión)', '{F}', 27),
('2.5.2', 2, '2. Manufactura de materiales', '2.5 Material eléctrico', 'Canalizaciones EMT, IMC y bandejas portacables', '{F}', 28),
('2.5.3', 2, '2. Manufactura de materiales', '2.5 Material eléctrico', 'Tableros eléctricos y breakers', '{F}', 29),
('2.5.4', 2, '2. Manufactura de materiales', '2.5 Material eléctrico', 'Tomacorrientes, apagadores y luminarias', '{F}', 30),
('2.6.1', 2, '2. Manufactura de materiales', '2.6 Madera y derivados', 'Madera para encofrado y andamiaje', '{F}', 31),
('2.6.2', 2, '2. Manufactura de materiales', '2.6 Madera y derivados', 'Tableros (plywood, MDF, MDP)', '{F}', 32),
('2.6.3', 2, '2. Manufactura de materiales', '2.6 Madera y derivados', 'Puertas, marcos y carpintería arquitectónica', '{F}', 33),
('2.7.1', 2, '2. Manufactura de materiales', '2.7 Prefabricación y ensamblaje', 'Estructuras modulares y paneles SIP', '{F}', 34),
('2.7.2', 2, '2. Manufactura de materiales', '2.7 Prefabricación y ensamblaje', 'Fachadas y ventanas preensambladas', '{F}', 35),
('3.1.1', 3, '3. Distribución y comercio de materiales', '3.1 Ferreterías y depósitos de materiales', 'Ferreterías industriales y generales', '{D}', 36),
('3.1.2', 3, '3. Distribución y comercio de materiales', '3.1 Ferreterías y depósitos de materiales', 'Depósitos y patios de materiales de construcción', '{D}', 37),
('3.2.1', 3, '3. Distribución y comercio de materiales', '3.2 Distribuidores especializados', 'Distribución de acero, cabillas y perfiles', '{D}', 38),
('3.2.2', 3, '3. Distribución y comercio de materiales', '3.2 Distribuidores especializados', 'Distribución de pinturas y recubrimientos', '{D}', 39),
('3.2.3', 3, '3. Distribución y comercio de materiales', '3.2 Distribuidores especializados', 'Distribución de materiales eléctricos e iluminación', '{D}', 40),
('3.2.4', 3, '3. Distribución y comercio de materiales', '3.2 Distribuidores especializados', 'Distribución hidrosanitaria, tuberías y sanitarios', '{D}', 41),
('3.2.5', 3, '3. Distribución y comercio de materiales', '3.2 Distribuidores especializados', 'Distribución de cerámicas, pisos y acabados', '{D}', 42),
('3.2.6', 3, '3. Distribución y comercio de materiales', '3.2 Distribuidores especializados', 'Distribución de maderas y tableros', '{D}', 43),
('3.2.7', 3, '3. Distribución y comercio de materiales', '3.2 Distribuidores especializados', 'Distribución de cemento, cal y pegos', '{D}', 44),
('3.2.8', 3, '3. Distribución y comercio de materiales', '3.2 Distribuidores especializados', 'Distribución de techos y cerramientos', '{D}', 45),
('3.3.1', 3, '3. Distribución y comercio de materiales', '3.3 Importadores de materiales', 'Importación de insumos y equipos de construcción', '{D}', 46),
('3.4.1', 3, '3. Distribución y comercio de materiales', '3.4 Transporte y fletes de carga', 'Transporte de carga y materiales de construcción', '{A}', 47),
('4.1.1', 4, '4. Servicios profesionales y técnicos', '4.1 Estudios previos', 'Topografía y geotecnia', '{S}', 48),
('4.1.2', 4, '4. Servicios profesionales y técnicos', '4.1 Estudios previos', 'Estudios de impacto ambiental', '{S}', 49),
('4.2.1', 4, '4. Servicios profesionales y técnicos', '4.2 Diseño e ingeniería', 'Arquitectura y BIM', '{S}', 50),
('4.2.2', 4, '4. Servicios profesionales y técnicos', '4.2 Diseño e ingeniería', 'Cálculo estructural', '{S}', 51),
('4.2.3', 4, '4. Servicios profesionales y técnicos', '4.2 Diseño e ingeniería', 'Proyectos MEP (eléctricos, sanitarios, mecánicos)', '{S}', 52),
('4.3.1', 4, '4. Servicios profesionales y técnicos', '4.3 Gestión y control', 'Permisología, licencias y trámites legales', '{S}', 53),
('4.3.2', 4, '4. Servicios profesionales y técnicos', '4.3 Gestión y control', 'Gerencia e inspección de obras', '{S}', 54),
('4.3.3', 4, '4. Servicios profesionales y técnicos', '4.3 Gestión y control', 'Laboratorios de control de calidad y ensayos', '{S}', 55),
('4.3.4', 4, '4. Servicios profesionales y técnicos', '4.3 Gestión y control', 'Seguridad industrial y dotación (EPP)', '{S}', 56),
('5.1.1', 5, '5. Ejecución de obra', '5.1 Constructoras y contratistas generales', 'Edificación residencial y comercial', '{C}', 57),
('5.1.2', 5, '5. Ejecución de obra', '5.1 Constructoras y contratistas generales', 'Obras civiles e infraestructura vial e industrial', '{C}', 58),
('5.2.1', 5, '5. Ejecución de obra', '5.2 Subcontratistas por especialidad', 'Movimiento de tierras, excavación y fundaciones', '{C}', 59),
('5.2.2', 5, '5. Ejecución de obra', '5.2 Subcontratistas por especialidad', 'Estructuras y obra negra', '{C}', 60),
('5.2.3', 5, '5. Ejecución de obra', '5.2 Subcontratistas por especialidad', 'Instalaciones MEP, HVAC y cableado estructurado', '{C}', 61),
('5.2.4', 5, '5. Ejecución de obra', '5.2 Subcontratistas por especialidad', 'Acabados, pintura, pisos, techos y paisajismo', '{C}', 62),
('6.1.1', 6, '6. Equipos, maquinaria y suministros especiales', '6.1 Maquinaria pesada y equipos', 'Venta de maquinaria pesada y equipos', '{F,A}', 63),
('6.1.2', 6, '6. Equipos, maquinaria y suministros especiales', '6.1 Maquinaria pesada y equipos', 'Alquiler de maquinaria pesada y equipos', '{F,A}', 64),
('6.2.1', 6, '6. Equipos, maquinaria y suministros especiales', '6.2 Andamios y encofrados', 'Venta y alquiler de andamios y encofrados', '{F,A}', 65),
('6.3.1', 6, '6. Equipos, maquinaria y suministros especiales', '6.3 Equipos de edificación y electromecánicos', 'Ascensores y escaleras mecánicas', '{F,S}', 66),
('6.3.2', 6, '6. Equipos, maquinaria y suministros especiales', '6.3 Equipos de edificación y electromecánicos', 'Climatización y HVAC industrial', '{F,S}', 67),
('6.3.3', 6, '6. Equipos, maquinaria y suministros especiales', '6.3 Equipos de edificación y electromecánicos', 'Bombas de agua e hidroneumáticos', '{F,S}', 68),
('6.3.4', 6, '6. Equipos, maquinaria y suministros especiales', '6.3 Equipos de edificación y electromecánicos', 'Transformadores y subestaciones', '{F,S}', 69),
('7.1.1', 7, '7. Financiamiento y comercialización', '7.1 Financiamiento y seguros', 'Banca, fiducias y crédito constructor', '{S}', 70),
('7.1.2', 7, '7. Financiamiento y comercialización', '7.1 Financiamiento y seguros', 'Seguros todo riesgo de construcción', '{S}', 71),
('7.2.1', 7, '7. Financiamiento y comercialización', '7.2 Inmobiliarias y corretaje', 'Inmobiliarias y comercialización de proyectos', '{S}', 72),
('7.2.2', 7, '7. Financiamiento y comercialización', '7.2 Inmobiliarias y corretaje', 'Avalúos y tasaciones inmobiliarias', '{S}', 73),
('8.1.1', 8, '8. Operación y fin de ciclo', '8.1 Facility management y mantenimiento', 'Facility management y mantenimiento de edificios', '{S}', 74),
('8.2.1', 8, '8. Operación y fin de ciclo', '8.2 Demolición y gestión de residuos', 'Demolición técnica de estructuras', '{C}', 75),
('8.2.2', 8, '8. Operación y fin de ciclo', '8.2 Demolición y gestión de residuos', 'Reciclaje de escombros (RCD) y disposición final', '{C}', 76)
ON CONFLICT (slug) DO NOTHING;