-- ==============================================================================
-- CARGA DE EMPRESAS Y ASOCIACIONES (106 FILAS -> 93 EMPRESAS ÚNICAS)
-- Fuente: cadena_construccion_clasificada.xlsx (Hoja 1)
-- ==============================================================================

-- 1. Actualizar esquema si no existen las columnas nuevas
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS whatsapp text;
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS productos_original text;
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS revisar boolean DEFAULT false;
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS nota_revision text;
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS direccion_precisa boolean DEFAULT true;
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS contacto_verificado boolean DEFAULT false;
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS fuente text;
ALTER TABLE public.empresas ADD COLUMN IF NOT EXISTS tipo_registro text DEFAULT 'empresa';

-- 2. Limpieza idempotente
DELETE FROM public.empresa_categorias;
DELETE FROM public.empresas;

INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000001', 'Bloquera Carabobo', 'Naguanagua', 'Zona Industrial Paramacay, Naguanagua, Estado Carabobo', true, NULL, NULL, NULL, 'Fabricación y comercialización de bloques de concreto y derivados para la construcción.', 'Fabricación y comercialización de bloques de concreto y derivados para la construcción.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000002', 'Bloquera Los Guayos', 'Los Guayos', 'Municipio Los Guayos, Estado Carabobo', false, NULL, NULL, NULL, 'Fabricación y comercialización de bloques de concreto y otros materiales de mampostería.', 'Fabricación y comercialización de bloques de concreto y otros materiales de mampostería.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000003', 'Bloquera y Concretera San Diego', 'San Diego', 'Municipio San Diego, Estado Carabobo', false, NULL, NULL, NULL, 'Fabricación y distribución de bloques de concreto, agregados y materiales para la construcción.', 'Fabricación y distribución de bloques de concreto, agregados y materiales para la construcción.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000004', 'Concretera de Occidente, C.A. (Concroca)', 'Libertador', 'Zona Industrial Municipal Norte / Municipio Libertador, Estado Carabobo', true, NULL, NULL, NULL, 'Planta de producción de concreto premezclado y elementos de concreto, operando en la zona industrial de Guacara. Planta de producción y comercialización de concreto premezclado y servicios afines.', 'Planta de producción de concreto premezclado y elementos de concreto, operando en la zona industrial de Guacara. | Planta de producción y comercialización de concreto premezclado y servicios afines.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000005', 'Corporación Cemento Nacional (Corpcemven) / Operaciones Planta Morón', 'Juan José Mora', 'Planta Morón', true, NULL, NULL, NULL, 'Planta de producción y molienda de cemento vinculada al sector cementero estatal venezolano ubicada en la zona industrial de Morón. cemento.', 'Planta de producción y molienda de cemento vinculada al sector cementero estatal venezolano ubicada en la zona industrial de Morón. | cemento', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000006', 'Concreto 7G', 'San Diego', 'Zona Industrial San Diego, Estado Carabobo', true, '+58 241 8710000', NULL, NULL, 'Empresa dedicada a la fabricación y comercialización de prefabricados de concreto, incluyendo bloques, tabelones y otros elementos para la construcción. Planta de producción y comercialización de concreto premezclado y servicios de bombeo.', 'Empresa dedicada a la fabricación y comercialización de prefabricados de concreto, incluyendo bloques, tabelones y otros elementos para la construcción. | Planta de producción y comercialización de concreto premezclado y servicios de bombeo.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000007', 'Concreto Conoaca, C.A.', 'Los Guayos', 'Zona Industrial Los Guayos, Municipio Los Guayos, Estado Carabobo', true, NULL, NULL, NULL, 'Planta de producción y distribución de concreto premezclado y productos derivados.', 'Planta de producción y distribución de concreto premezclado y productos derivados.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000008', 'Concreto Industrial de Venezuela (Cinca)', 'Guacara', 'Zona Industrial Guacara, Estado Carabobo', true, NULL, NULL, NULL, 'Planta de producción y comercialización de concreto premezclado y servicios afines en la región central de Venezuela.', 'Planta de producción y comercialización de concreto premezclado y servicios afines en la región central de Venezuela.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000009', 'Concreto Los Andes', 'Libertador', 'Municipio Libertador, Estado Carabobo, Venezuela', true, NULL, NULL, NULL, 'Empresa dedicada a la fabricación y comercialización de prefabricados de concreto, incluyendo bloques, adoquines y otros elementos para la construcción.', 'Empresa dedicada a la fabricación y comercialización de prefabricados de concreto, incluyendo bloques, adoquines y otros elementos para la construcción.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000010', 'Concreto Miranda, C.A.', 'Miranda', 'Municipio Miranda, Estado Carabobo', false, NULL, NULL, NULL, 'Empresa dedicada a la fabricación de bloques de concreto y derivados en la región.', 'Empresa dedicada a la fabricación de bloques de concreto y derivados en la región.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000011', 'Concreto Nororiental, C.A. (Conorca) - Planta Naguanagua / Carabobo', 'Naguanagua', 'Zona Industrial Paramacay, Municipio Naguanagua, Estado Carabobo', true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000012', 'Concreto Occidental, C.A. (Conocca)', 'Valencia', 'Zona Industrial Municipal Sur, Valencia, Estado Carabobo', true, NULL, NULL, NULL, 'Empresa dedicada a la fabricación, venta y distribución de concreto premezclado y servicios afines para la construcción.', 'Empresa dedicada a la fabricación, venta y distribución de concreto premezclado y servicios afines para la construcción.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000013', 'Concreto Premezclado C.A. (Conpreca)', 'Valencia', 'Zona Industrial Municipal Sur, Valencia, Estado Carabobo', true, '+58 241 8323811', NULL, NULL, 'Empresa dedicada a la fabricación y comercialización de concreto premezclado y elementos prefabricados para la construcción.', 'Empresa dedicada a la fabricación y comercialización de concreto premezclado y elementos prefabricados para la construcción.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000014', 'Preconcretos, C.A.', 'Valencia', 'Valencia, Estado Carabobo', false, NULL, NULL, NULL, 'Empresa dedicada a la fabricación, venta y suministro de concreto premezclado y despacho con camionesmixter. Planta de producción y suministro de concreto premezclado y bombeo de concreto en la región central.', 'Empresa dedicada a la fabricación, venta y suministro de concreto premezclado y despacho con camionesmixter. | Planta de producción y suministro de concreto premezclado y bombeo de concreto en la región central.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000015', 'Premezclados Carabobo', 'San Diego', 'Municipio San Diego, Carabobo', false, NULL, NULL, NULL, 'Fabricación y suministro de concreto premezclado para el sector construcción.', 'Fabricación y suministro de concreto premezclado para el sector construcción.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000016', 'Cerámica Carabobo', 'Valencia', 'Zona Industrial Municipal Norte, Valencia, Estado Carabobo', true, '+58 241 8303111', NULL, NULL, 'Comercialización y distribución de pisos, porcelanatos, piezas sanitarias y grifería. Fabricante de revestimientos cerámicos, pisos y productos de arcilla para la construcción. Fabricante y distribuidor de cables eléctricos de baja y media tensión.', 'Comercialización y distribución de pisos, porcelanatos, piezas sanitarias y grifería. | Fabricante de revestimientos cerámicos, pisos y productos de arcilla para la construcción. | Fabricante y distribuidor de cables eléctricos de baja y media tensión.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000017', 'Construarca', 'Los Guayos', 'Zona Industrial Los Guayos, Estado Carabobo', true, NULL, NULL, NULL, 'Fabricante y distribuidor de productos de arcilla roja para la construcción, incluyendo ladrillos, bloques y tejas.', 'Fabricante y distribuidor de productos de arcilla roja para la construcción, incluyendo ladrillos, bloques y tejas.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000018', 'Inversiones Terracotta, C.A.', 'San Joaquín', 'Zona Industrial San Joaquín, Estado Carabobo', true, NULL, NULL, NULL, 'Fabricación y comercialización de productos de arcilla roja, incluyendo ladrillos y tejas para la construcción.', 'Fabricación y comercialización de productos de arcilla roja, incluyendo ladrillos y tejas para la construcción.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000019', 'Aceros de Venezuela (Acervenca)', 'San Joaquín', 'Zona Industrial San Joaquín, Estado Carabobo', true, NULL, NULL, NULL, 'Planta de fabricación, procesamiento y comercialización de productos siderúrgicos, perfiles de acero y derivados para la construcción en el municipio San Joaquín, estado Carabobo.', 'Planta de fabricación, procesamiento y comercialización de productos siderúrgicos, perfiles de acero y derivados para la construcción en el municipio San Joaquín, estado Carabobo.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000020', 'Sideroca (Siderúrgica Venezolana, S.A.)', 'Valencia', 'Zona Industrial Las Tejerías / Valencia (Carabobo)', true, NULL, NULL, NULL, 'Fabricación de tubos de acero, productos tubulares y derivados para la industria y la construcción.', 'Fabricación de tubos de acero, productos tubulares y derivados para la industria y la construcción.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000021', 'Sidetur - Planta Casima / Tocuyito', 'Libertador', 'Zona Industrial Tocuyito, Municipio Libertador, Estado Carabobo', true, NULL, NULL, NULL, 'Importante fabricante y procesador de productos de acero para la construcción, incluyendo cabillas y acero de refuerzo.', 'Importante fabricante y procesador de productos de acero para la construcción, incluyendo cabillas y acero de refuerzo.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000022', 'Sidor - Planta Guacara (Centro de Distribución / Operaciones)', 'Guacara', 'Zona Industrial Guacara, Estado Carabobo', true, NULL, NULL, NULL, 'Centro operativo y de distribución asociado a la principal siderúrgica del país para la entrega de productos de acero. Fabricante y distribuidor de productos siderúrgicos.', 'Centro operativo y de distribución asociado a la principal siderúrgica del país para la entrega de productos de acero. | Fabricante y distribuidor de productos siderúrgicos.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000023', 'C.A. Proyectos Metalúrgicos Prometa', 'San Joaquín', 'Zona Industrial San Joaquín, Estado Carabobo', true, NULL, NULL, NULL, 'Diseño, fabricación y montaje de estructuras metálicas, galpones y perfiles de acero.', 'Diseño, fabricación y montaje de estructuras metálicas, galpones y perfiles de acero.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000024', 'Estructuras Metálicas Carabobo (Estructurca)', 'Valencia', 'Zona Industrial El Piñonal / Urbanización Industrial Valencia', true, '+58 241 8712345', NULL, NULL, 'Fabricación y montaje de estructuras metálicas, galpones industriales, perfiles y cerchas de acero.', 'Fabricación y montaje de estructuras metálicas, galpones industriales, perfiles y cerchas de acero.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000025', 'Estructuras Metálicas y Galpones (Servicios Generales Industriales)', 'San Diego', 'Zona Industrial San Diego, Carabobo', true, NULL, NULL, NULL, 'Fabricación y montaje de estructuras metálicas, galpones industriales y perfiles.', 'Fabricación y montaje de estructuras metálicas, galpones industriales y perfiles.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000026', 'Inversiones R&G C.A.', 'San Diego', 'Municipio San Diego, Estado Carabobo', false, NULL, NULL, NULL, 'Empresa dedicada a la fabricación, diseño y montaje de estructuras metálicas, galpones y obras civiles.', 'Empresa dedicada a la fabricación, diseño y montaje de estructuras metálicas, galpones y obras civiles.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000027', 'Metalúrgica M&G 2000, C.A.', 'Guacara', 'Zona Industrial Guacara, Estado Carabobo', true, '+58 245 5641234', NULL, NULL, 'Empresa dedicada a la fabricación, diseño y montaje de estructuras metálicas, galpones y perfiles de acero.', 'Empresa dedicada a la fabricación, diseño y montaje de estructuras metálicas, galpones y perfiles de acero.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000028', 'Siderúrgica Venezolana S.A. (Sivensa) - Plantas operativas en la región', 'Libertador', 'Estado Carabobo (Zona industrial con influencia en municipio Libertador)', true, NULL, NULL, NULL, 'Fabricación y comercialización de productos de acero, barras y perfiles.', 'Fabricación y comercialización de productos de acero, barras y perfiles.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000029', 'Corimon Pinturas Montana, C.A.', 'Valencia', 'Av. Anton Philips, Zona Industrial Los Guayos - Valencia, Carabobo', true, '+58 241 8391111', '+58 412 0001122', 'atencion@corimon.com', 'Comercialización de pinturas arquitectónicas, esmaltes, impermeabilizantes y recubrimientos. Esmaltes. Línea industrial y marina. Masillas. Pintura arquitectónica. Planta de fabricación de pinturas, esmaltes, impermeabilizantes y recubrimientos de la corporación Corimon. Venta de pinturas tipo caucho, esmaltes, anticorrosivos y productos para la construcción.', 'Comercialización de pinturas arquitectónicas, esmaltes, impermeabilizantes y recubrimientos. | Esmaltes | Línea industrial y marina | Masillas | Pintura arquitectónica | Planta de fabricación de pinturas, esmaltes, impermeabilizantes y recubrimientos de la corporación Corimon. | Venta de pinturas tipo caucho, esmaltes, anticorrosivos y productos para la construcción.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000030', 'Mavesa / Pinturas (Operaciones Guacara - Empresas Polar)', 'Guacara', 'Autopista Regional del Centro, Kilómetro 134, Zona Industrial Guacara, Edo. Carabobo', true, NULL, NULL, NULL, 'Complejo industrial de manufactura que incluye líneas de producción y almacenamiento de derivados químicos y recubrimientos.', 'Complejo industrial de manufactura que incluye líneas de producción y almacenamiento de derivados químicos y recubrimientos.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000031', 'Pineco (Pinturas Pineco)', 'Valencia', 'Zona Industrial Municipal Norte, Valencia, Estado Carabobo', true, '+58 241 8342415', NULL, NULL, 'Fabricante de pinturas tipo caucho, esmaltes y productos para la construcción.', 'Fabricante de pinturas tipo caucho, esmaltes y productos para la construcción.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000032', 'Pinturas Flamuko, C.A.', 'Valencia', 'Parcela B-14, Zona Industrial Municipal Sur, Valencia, Carabobo', true, '+58 241 8741500', '+58 414 4332211', 'contacto@flamuko.com', 'Esmaltes sintéticos. Fondos anticorrosivos. Pintura epóxica. Pinturas de caucho.', 'Esmaltes sintéticos | Fondos anticorrosivos | Pintura epóxica | Pinturas de caucho', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000033', 'Pinturas Montana (Corimon)', 'Valencia', 'Zona Industrial El Piñonal / Av. Henry Ford, Valencia, Estado Carabobo', true, '+58 241 8711011', NULL, NULL, 'Fabricación y distribución de pinturas, esmaltes, impermeabilizantes y recubrimientos.', 'Fabricación y distribución de pinturas, esmaltes, impermeabilizantes y recubrimientos.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000034', 'Pinturasarsa (Pinturas Antillas / ARSA)', 'Los Guayos', 'Zona Industrial Los Guayos, Calle 3, Galpón Nro. 4, Municipio Los Guayos, Carabobo', true, '+58 241 8381234', NULL, NULL, 'Fabricante y distribuidor de pinturas, impermeabilizantes, esmaltes y recubrimientos para la construcción e industria.', 'Fabricante y distribuidor de pinturas, impermeabilizantes, esmaltes y recubrimientos para la construcción e industria.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000035', 'Sherwin-Williams de Venezuela (Planta Los Guayos)', 'Los Guayos', 'Zona Industrial Los Guayos, Municipio Los Guayos, Estado Carabobo', true, '+58 241 8301111', NULL, NULL, 'Fabricación y comercialización de pinturas arquitectónicas, industriales, automotrices y recubrimientos en general. Planta de fabricación, distribución y comercialización de pinturas arquitectónicas, industriales, automotrices y recubrimientos.', 'Fabricación y comercialización de pinturas arquitectónicas, industriales, automotrices y recubrimientos en general. | Planta de fabricación, distribución y comercialización de pinturas arquitectónicas, industriales, automotrices y recubrimientos.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000036', 'Alambres y Cables Venezolanos, C.A. (Alcave)', 'Guacara', 'Zona Industrial Guacara, Calle Sur 3, Lote 4, Guacara, Estado Carabobo', true, '+58 245 5712311', NULL, NULL, 'Fabricante de conductores eléctricos y alambres de cobre y aluminio.', 'Fabricante de conductores eléctricos y alambres de cobre y aluminio.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000037', 'Cabelum (Industria Venezolana de Cables Eléctricos, C.A.)', 'Libertador', 'Zona Industrial Castillito, Municipio Libertador, Estado Carabobo', true, NULL, NULL, NULL, 'Fabricante de conductores eléctricos de aluminio y aleaciones de aluminio para el sector eléctrico.', 'Fabricante de conductores eléctricos de aluminio y aleaciones de aluminio para el sector eléctrico.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000038', 'Conductores Cabel, C.A.', 'Guacara', 'Zona Industrial Guacara, Estado Carabobo', true, '+58 245 5611111', NULL, NULL, 'Fabricante de cables eléctricos de alta y baja tensión.', 'Fabricante de cables eléctricos de alta y baja tensión.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000039', 'Conduven', 'San Joaquín', 'Zona Industrial San Joaquín, Estado Carabobo', true, '58243911', NULL, NULL, 'Fabricante de tubos de acero y perfiles estructurales, ampliamente utilizados en instalaciones eléctricas y bandejas portacables industriales.', 'Fabricante de tubos de acero y perfiles estructurales, ampliamente utilizados en instalaciones eléctricas y bandejas portacables industriales.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000040', 'Serraser - Aserradero y Maderera (Referencia local Morón / Juan José Mora)', 'Juan José Mora', 'Municipio Juan José Mora, Morón, Estado Carabobo', true, NULL, NULL, NULL, 'Empresa vinculada al procesamiento y comercialización de madera, servicios de aserradero y productos derivados para la construcción en la región de Carabobo.', 'Empresa vinculada al procesamiento y comercialización de madera, servicios de aserradero y productos derivados para la construcción en la región de Carabobo.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000041', 'Vencemos (Cementos Sika / Cemex / Plantas de prefabricados asociadas - verificar distribuidor local)', 'Valencia', 'Zona Industrial El Piñonal / Valencia, Estado Carabobo', true, NULL, NULL, NULL, 'Fabricación y distribución de materiales de construcción, cemento y derivados.', 'Fabricación y distribución de materiales de construcción, cemento y derivados.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000042', 'Distribuidora Ferretera Central (Diferca)', 'Valencia', 'Zona Industrial Castillito, Valencia/San Diego, Estado Carabobo', true, '+58 241 8716522', NULL, NULL, 'Distribución mayorista de clavos, alambres, pernos, tornillería industrial, herramientas de corte y abrasivos.', 'Distribución mayorista de clavos, alambres, pernos, tornillería industrial, herramientas de corte y abrasivos.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000043', 'Ferretería Beco, C.A.', 'Valencia', 'Zona Industrial Municipal I, Av. Norte-Sur 4, Valencia, Carabobo', true, '+58 241 8328111', NULL, NULL, 'Suministro de ferretería en general, herramientas industriales, clavos, tornillos, guayas, mallas y materiales de construcción para proyectos comerciales e industriales.', 'Suministro de ferretería en general, herramientas industriales, clavos, tornillos, guayas, mallas y materiales de construcción para proyectos comerciales e industriales.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000044', 'Ferretería EPA San Diego', 'San Diego', 'Avenida Don Julio Centeno, Municipio San Diego, Estado Carabobo', true, '+58 500 3720000', NULL, NULL, 'Gran superficie de ferretería, construcción, hogar y bricolaje, incluyendo secciones de tornillería, clavos, anclajes y herramientas industriales.', 'Gran superficie de ferretería, construcción, hogar y bricolaje, incluyendo secciones de tornillería, clavos, anclajes y herramientas industriales.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000045', 'Ferretería EPA, C.A.', 'Valencia', 'Av. Michelena, Distribuidor San Blas, Valencia, Carabobo', true, '+58 241 8131000', '+58 414 3410000', 'atencionalcliente@ve.epa.biz', 'Clavos y pernos. Herrajes. Herramientas eléctricas. Tornillos y anclajes.', 'Clavos y pernos | Herrajes | Herramientas eléctricas | Tornillos y anclajes', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000046', 'Ferretería Industrial La Guacamaya, C.A.', 'Valencia', 'Zona Industrial La Guacamaya, Valencia, Estado Carabobo, Venezuela', true, '+58 241 8583011', NULL, NULL, 'Venta al mayor y detal de insumos ferreteros industriales, sistemas de anclaje, tornillería de alta resistencia y herrajes.', 'Venta al mayor y detal de insumos ferreteros industriales, sistemas de anclaje, tornillería de alta resistencia y herrajes.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000047', 'Ferretería La Campana Naguanagua', 'Naguanagua', 'Av. Universidad, C.C. La Campana, Naguanagua, Carabobo', true, '+58 241 8671122', '+58 424 4005566', NULL, 'Cerraduras. Clavos para concreto. Herramientas manuales. Tornillos autorroscantes.', 'Cerraduras | Clavos para concreto | Herramientas manuales | Tornillos autorroscantes', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000048', 'Ferretería y Materiales Mariara', 'Diego Ibarra', 'Municipio Mariara, Estado Carabobo', false, NULL, NULL, NULL, 'Comercialización de materiales de construcción, ferretería general, tornillería y herramientas para la industria y el hogar.', 'Comercialización de materiales de construcción, ferretería general, tornillería y herramientas para la industria y el hogar.', NULL, NULL, true, 'Municipio registrado originalmente como Mariara (capital del Municipio Diego Ibarra). Requiere verificación.', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000049', 'Ferretería y Materiales de Construcción en Montalbán (Comercios locales y distribuidores)', 'Montalbán', 'Municipio Montalbán, Estado Carabobo', false, NULL, NULL, NULL, 'Debido a la naturaleza rural y semi-urbana del municipio Montalbán en el estado Carabobo, la comercialización de pinturas, esmaltes y anticorrosivos se realiza principalmente a través de ferreterías l.', 'Debido a la naturaleza rural y semi-urbana del municipio Montalbán en el estado Carabobo, la comercialización de pinturas, esmaltes y anticorrosivos se realiza principalmente a través de ferreterías l', NULL, NULL, true, 'Referencia genérica: identificar la empresa real', false, 'cadena_construccion_clasificada.xlsx', 'referencia_generica');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000050', 'Ferretería y Pinturas Comercializadoras locales de Bejuma', 'Bejuma', 'Municipio Bejuma, Estado Carabobo', false, NULL, NULL, NULL, 'Búsqueda en bases de datos comerciales e índice de empresas para Bejuma, Carabobo, enfocado en el sector ferretero y de recubrimientos.', 'Búsqueda en bases de datos comerciales e índice de empresas para Bejuma, Carabobo, enfocado en el sector ferretero y de recubrimientos.', NULL, NULL, true, 'Referencia genérica: identificar la empresa real', false, 'cadena_construccion_clasificada.xlsx', 'referencia_generica');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000051', 'Ferretería y Tornillería Industrial (Representaciones y Servicios asociados a la zona industrial de Los Guayos)', 'Los Guayos', 'Zona Industrial Los Guayos, Municipio Los Guayos, Estado Carabobo', true, NULL, NULL, NULL, 'Comercialización de tornillería, clavos, anclajes y ferretería industrial en general para el sector manufacturero y de construcción.', 'Comercialización de tornillería, clavos, anclajes y ferretería industrial en general para el sector manufacturero y de construcción.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000052', 'Ferretería y Tornillería Industrial (Representaciones y Suministros)', 'Guacara', 'Zona Industrial Guacara, Estado Carabobo', true, NULL, NULL, NULL, 'Comercialización de tornillería, clavos, anclajes y ferretería industrial para el sector manufacturero.', 'Comercialización de tornillería, clavos, anclajes y ferretería industrial para el sector manufacturero.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000053', 'Ferretería y Tuberías La 190, C.A.', 'Naguanagua', 'Avenida 190, Naguanagua, Estado Carabobo', true, NULL, NULL, NULL, 'Comercialización de materiales de ferretería general, industrial, tuberías y conexos.', 'Comercialización de materiales de ferretería general, industrial, tuberías y conexos.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000054', 'Inversiones R&G (Representaciones y Gaskets / Suministros Industriales)', 'San Diego', 'Municipio San Diego, Estado Carabobo', false, NULL, NULL, NULL, 'Comercialización de suministros industriales, ferretería, tornillería y repuestos para el sector manufacturero y de construcción en la región.', 'Comercialización de suministros industriales, ferretería, tornillería y repuestos para el sector manufacturero y de construcción en la región.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000055', 'Tornillos Carabobo, C.A.', 'Valencia', 'Av. Michelena, C.C. Los Jarales / Zona Industrial San Luis, Valencia, Estado Carabobo', true, '+58 241 8321288', NULL, NULL, 'Empresa especializada en la venta y distribución de tornillería industrial, anclajes, tuercas, arandelas y herramientas para el sector industrial y automotriz. tornillos.', 'Empresa especializada en la venta y distribución de tornillería industrial, anclajes, tuercas, arandelas y herramientas para el sector industrial y automotriz. | tornillos', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000056', 'Tornillos Valencia, C.A.', 'Valencia', 'Av. Ernesto Branger, Galpón 4, Zona Industrial Municipal, Valencia', true, '+58 241 8324567', '+58 414 4123344', 'ventas@tornillosvalencia.com.ve', 'Arandelas. Espárragos B7. Tornillería industrial grado 5 y 8. Tuercas hexagonales.', 'Arandelas | Espárragos B7 | Tornillería industrial grado 5 y 8 | Tuercas hexagonales', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000057', 'Tornillos e Inversiones Valencia, C.A. (Tornival)', 'Valencia', 'Av. Bolivar Norte, Sector San José, Valencia, Carabobo', true, '+58 241 8241512', NULL, NULL, 'Comercialización de tornillería en general, pernos, espárragos, anclajes mecánicos y químicos, y herramientas de fijación industrial. fijaciones. tornillos.', 'Comercialización de tornillería en general, pernos, espárragos, anclajes mecánicos y químicos, y herramientas de fijación industrial. | fijaciones | tornillos', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000058', 'Acero de Carabobo, C.A. (Acerocara)', 'Libertador', 'Zona Industrial Municipal Sur, Valencia, Estado Carabobo (operando en el eje metropolitano que incluye al municipio Libertador)', true, '+58 241 8321111', NULL, NULL, 'Empresa dedicada a la comercialización y distribución de productos siderúrgicos, perfiles y acero para la construcción. Empresa dedicada al procesamiento, distribución y comercialización de productos siderúrgicos y perfiles de acero. Fabricante de conductores eléctricos de aluminio y aleaciones para el sector eléctrico. Fabricante y comercializador de pinturas arquitectónicas, industriales, automotrices y recubrimientos.', 'Empresa dedicada a la comercialización y distribución de productos siderúrgicos, perfiles y acero para la construcción. | Empresa dedicada al procesamiento, distribución y comercialización de productos siderúrgicos y perfiles de acero. | Fabricante de conductores eléctricos de aluminio y aleaciones para el sector eléctrico. | Fabricante y comercializador de pinturas arquitectónicas, industriales, automotrices y recubrimientos.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000059', 'Acero de Guayana, C.A. (Acerguay)', 'Los Guayos', 'Zona Industrial Los Guayos, Municipio Los Guayos, Estado Carabobo.', true, NULL, NULL, NULL, 'Empresa dedicada al procesamiento, comercialización y distribución de productos siderúrgicos y acero para la construcción, incluyendo cabillas y materiales ferrosos.', 'Empresa dedicada al procesamiento, comercialización y distribución de productos siderúrgicos y acero para la construcción, incluyendo cabillas y materiales ferrosos.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000060', 'Acero de Guayana, C.A. (Agunca) / Sucursales y operaciones asociadas en Carabobo', 'San Diego', 'Zona Industrial El Recreo, Municipio San Diego, Estado Carabobo', true, NULL, NULL, NULL, 'Empresa dedicada al procesamiento y comercialización de productos siderúrgicos, acero de refuerzo, cabillas y materiales para la construcción.', 'Empresa dedicada al procesamiento y comercialización de productos siderúrgicos, acero de refuerzo, cabillas y materiales para la construcción.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000061', 'Acero de Occidente, C.A. (Acerooccidente)', 'Naguanagua', 'Avenida 100 Bolívar, Zona Industrial Paramacay, Naguanagua, Estado Carabobo', true, '+58 241 8661234', NULL, NULL, 'Empresa comercializadora de productos siderúrgicos, perfiles de acero, vigas y derivados para la construcción y la industria.', 'Empresa comercializadora de productos siderúrgicos, perfiles de acero, vigas y derivados para la construcción y la industria.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000062', 'Acero de Valencia, C.A.', 'Valencia', 'Zona Industrial Municipal Sur, Valencia, Estado Carabobo', true, '+58 241 8345511', NULL, NULL, 'Comercialización y distribución de productos siderúrgicos, perfiles de acero y materiales para la construcción.', 'Comercialización y distribución de productos siderúrgicos, perfiles de acero y materiales para la construcción.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000063', 'Acero de Valencia, C.A. (Acerival)', 'Valencia', 'Zona Industrial Municipal Norte, Valencia, Estado Carabobo', true, '+58 241 8328811', NULL, NULL, 'Empresa comercializadora de productos siderúrgicos, incluyendo perfiles de acero, vigas y planchas para la industria y construcción.', 'Empresa comercializadora de productos siderúrgicos, incluyendo perfiles de acero, vigas y planchas para la industria y construcción.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000064', 'Aceros de Carabobo, C.A.', 'Los Guayos', 'Zona Industrial Los Guayos, Estado Carabobo, Venezuela', true, NULL, NULL, NULL, 'Empresa dedicada al procesamiento, venta y distribución de acero, perfiles metálicos y planchas. acero. materiales ferreteros.', 'Empresa dedicada al procesamiento, venta y distribución de acero, perfiles metálicos y planchas. | acero | materiales ferreteros', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000065', 'Ferretería Carvajal, C.A.', 'Valencia', 'Av. Las Ferias, Valencia, Estado Carabobo', true, '+58 241 8341234', NULL, NULL, 'Comercialización de materiales de construcción, perfiles tubulares, ángulos y chapas de acero.', 'Comercialización de materiales de construcción, perfiles tubulares, ángulos y chapas de acero.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000066', 'Ferretería y Materiales Naguanagua 2000', 'Naguanagua', 'Avenida Universidad, Naguanagua, Estado Carabobo', true, '+58 241 8615555', NULL, NULL, 'Comercio detal y mayor de materiales de construcción, incluyendo cabillas, varillas y mallas electrosoldadas.', 'Comercio detal y mayor de materiales de construcción, incluyendo cabillas, varillas y mallas electrosoldadas.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000067', 'Ferretería y Materiales de Construcción en la zona de Bejuma', 'Bejuma', 'Municipio Bejuma, Estado Carabobo, Venezuela', true, NULL, NULL, NULL, 'Comercialización de materiales de construcción, incluyendo cemento, cal y agregados para obras civiles.', 'Comercialización de materiales de construcción, incluyendo cemento, cal y agregados para obras civiles.', NULL, NULL, true, 'Referencia genérica: identificar la empresa real', false, 'cadena_construccion_clasificada.xlsx', 'referencia_generica');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000068', 'Inversiones Aceros Guayos, C.A.', 'Los Guayos', 'Municipio Los Guayos, Estado Carabobo', false, NULL, NULL, NULL, 'Comercialización y distribución de productos siderúrgicos, perfiles de acero, vigas y derivados para la construcción.', 'Comercialización y distribución de productos siderúrgicos, perfiles de acero, vigas y derivados para la construcción.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000069', 'Inversiones y Suministros Aceroflex, C.A.', 'Guacara', 'Carretera Nacional Guacara-Los Guayos, Sector El Cabrito, Guacara, Carabobo', true, NULL, NULL, NULL, 'Distribución y comercialización de planchas de acero, perfiles tubulares y vigas para el sector industrial y de construcción.', 'Distribución y comercialización de planchas de acero, perfiles tubulares y vigas para el sector industrial y de construcción.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000070', 'Inversiones y Suministros Metalúrgicos (Insurnet)', 'Los Guayos', 'Municipio Los Guayos, Estado Carabobo.', false, NULL, NULL, NULL, 'Comercialización de productos de acero, perfiles y materiales destinados al sector metalmecánico y de construcción en la región.', 'Comercialización de productos de acero, perfiles y materiales destinados al sector metalmecánico y de construcción en la región.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000071', 'Inversiones y Suministros Metálicos (Suministros Industriales Guacara)', 'Guacara', 'Zona Industrial El Nepe, Guacara, Estado Carabobo', true, NULL, NULL, NULL, 'Comercialización de perfiles de acero, productos siderúrgicos y materiales para la construcción metálica.', 'Comercialización de perfiles de acero, productos siderúrgicos y materiales para la construcción metálica.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000072', 'Mundo Cerámico', 'Naguanagua', 'Avenida Universidad, Naguanagua, Carabobo', true, '+58 241 8081234', NULL, NULL, 'Aserradero, comercialización de madera y derivados para la construcción y carpintería. Comercialización de pisos, porcelanatos, revestimientos cerámicos y piezas sanitarias.', 'Aserradero, comercialización de madera y derivados para la construcción y carpintería. | Comercialización de pisos, porcelanatos, revestimientos cerámicos y piezas sanitarias.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000073', 'Ferretería y Materiales San Diego', 'San Diego', 'Municipio San Diego, Estado Carabobo', false, NULL, NULL, NULL, 'Comercialización de materiales de construcción, cemento, cal y agregados en el municipio San Diego.', 'Comercialización de materiales de construcción, cemento, cal y agregados en el municipio San Diego.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000074', 'Ferretería y Materiales de Construcción (Directorio Comercial Local)', 'Naguanagua', 'Municipio Naguanagua, Estado Carabobo', false, NULL, NULL, NULL, 'Comercialización de materiales para la construcción incluyendo cemento, cal y yeso en la región de Carabobo.', 'Comercialización de materiales para la construcción incluyendo cemento, cal y yeso en la región de Carabobo.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000075', 'Ferretería EPA - Los Guayos', 'Los Guayos', 'Autopista Regional del Centro, sector Los Guayos, Valencia, Estado Carabobo', true, '+58 241 8740111', NULL, NULL, 'Fabricante de tubos de acero y perfiles, con presencia y operaciones industriales en la zona de Carabobo, suministrando materiales para la industria eléctrica y de construcción. Fabricante y distribuidor líder en Venezuela de revestimientos cerámicos, pisos, paredes y piezas sanitarias. Gran centro de suministros para la construcción, hogar y ferretería, que incluye departamentos de pisos, revestimientos cerámicos, porcelanatos y piezas sanitarias.', 'Fabricante de tubos de acero y perfiles, con presencia y operaciones industriales en la zona de Carabobo, suministrando materiales para la industria eléctrica y de construcción. | Fabricante y distribuidor líder en Venezuela de revestimientos cerámicos, pisos, paredes y piezas sanitarias. | Gran centro de suministros para la construcción, hogar y ferretería, que incluye departamentos de pisos, revestimientos cerámicos, porcelanatos y piezas sanitarias.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000076', 'Inversiones Ceramicas', 'Diego Ibarra', 'Municipio Diego Ibarra, Estado Carabobo', false, NULL, NULL, NULL, 'Empresa vinculada al sector de cerámicas y afines en el estado Carabobo.', 'Empresa vinculada al sector de cerámicas y afines en el estado Carabobo.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000077', 'Inversiones Gres, C.A.', 'San Diego', 'Urbanización Industrial Los Jarales, Municipio San Diego, Estado Carabobo', true, '58241871', NULL, NULL, 'Empresa comercializadora de revestimientos, pisos, porcelanatos y materiales para la construcción.', 'Empresa comercializadora de revestimientos, pisos, porcelanatos y materiales para la construcción.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000078', 'Suministros y Materiales de Construcción operando en la zona (Ferremateriales locales)', 'Juan José Mora', 'Municipio Juan José Mora (Morón), Estado Carabobo', true, NULL, NULL, NULL, 'Comercios y ferreterías locales que distribuyen materiales de construcción básicos, incluyendo revestimientos, cemento y derivados en el eje costero de Carabobo.', 'Comercios y ferreterías locales que distribuyen materiales de construcción básicos, incluyendo revestimientos, cemento y derivados en el eje costero de Carabobo.', NULL, NULL, true, 'Referencia genérica: identificar la empresa real', false, 'cadena_construccion_clasificada.xlsx', 'referencia_generica');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000079', 'Inversiones Madereras 2000', 'Valencia', 'Av. Las Ferias, Valencia, Estado Carabobo', true, NULL, NULL, NULL, 'Venta al mayor y detal de madera nacional e importada, listones, plywood y materiales para encofrado y construcción.', 'Venta al mayor y detal de madera nacional e importada, listones, plywood y materiales para encofrado y construcción.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000080', 'Inversiones y Maderas C.A.', 'Carlos Arvelo', 'Municipio Carlos Arvelo, Estado Carabobo', false, NULL, NULL, NULL, 'Comercialización de madera, tableros y materiales para la construcción en el estado Carabobo.', 'Comercialización de madera, tableros y materiales para la construcción en el estado Carabobo.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000081', 'Maderas y Acabados Los Pinos', 'Naguanagua', 'Municipio Naguanagua, Estado Carabobo', false, NULL, NULL, NULL, 'Comercialización de madera, tableros y servicios de carpintería en la región.', 'Comercialización de madera, tableros y servicios de carpintería en la región.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000082', 'Maderas y Acabados Los Pinos (Referencia regional Carabobo)', 'Diego Ibarra', 'Estado Carabobo (Operaciones regionales)', false, NULL, NULL, NULL, 'Proveedor de madera, tableros y servicios de carpintería con cobertura en el estado Carabobo.', 'Proveedor de madera, tableros y servicios de carpintería con cobertura en el estado Carabobo.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000083', 'Maderas y Aserradero Bejuma', 'Bejuma', 'Bejuma, Estado Carabobo', false, NULL, NULL, NULL, 'Comercialización de madera y productos derivados para la construcción y carpintería en el municipio Bejuma.', 'Comercialización de madera y productos derivados para la construcción y carpintería en el municipio Bejuma.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000084', 'Maderas y Tableros C.A. (Madtica)', 'Valencia', 'Zona Industrial Municipal Norte, Valencia, Estado Carabobo', true, '+58 241 8324411', NULL, NULL, 'Comercialización y distribución de tableros de madera, MDF, aglomerado y derivados para la industria del mueble y la carpintería.', 'Comercialización y distribución de tableros de madera, MDF, aglomerado y derivados para la industria del mueble y la carpintería.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000085', 'C.A. Proyectos y Suministros Eléctricos (Prosyel)', 'Naguanagua', 'Avenida Universidad, Naguanagua, Estado Carabobo', true, NULL, NULL, NULL, 'Empresa dedicada al suministro de materiales eléctricos, tableros y equipos para el sector industrial y comercial.', 'Empresa dedicada al suministro de materiales eléctricos, tableros y equipos para el sector industrial y comercial.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000086', 'Corporación Suministros Eléctricos C.A. (Corposuministros)', 'San Diego', 'Zona Industrial La Esmeralda, San Diego, Carabobo.', true, NULL, NULL, NULL, 'Proveedor de materiales y equipos eléctricos para la industria, incluyendo iluminación, cables y componentes de baja y mediana tensión.', 'Proveedor de materiales y equipos eléctricos para la industria, incluyendo iluminación, cables y componentes de baja y mediana tensión.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000087', 'Ferretotal Morón', 'Juan José Mora', 'Municipio Juan José Mora, Morón, Estado Carabobo', true, NULL, NULL, NULL, 'Comercialización de materiales de ferretería, construcción, herramientas y productos eléctricos para el hogar e industria.', 'Comercialización de materiales de ferretería, construcción, herramientas y productos eléctricos para el hogar e industria.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000088', 'Inversiones 1253, C.A.', 'San Diego', 'Urbanización Industrial Los Guayabitos, Municipio San Diego, Estado Carabobo.', true, NULL, NULL, NULL, 'Empresa dedicada a la comercialización de materiales eléctricos industriales, cables, tableros y equipos relacionados en el estado Carabobo.', 'Empresa dedicada a la comercialización de materiales eléctricos industriales, cables, tableros y equipos relacionados en el estado Carabobo.', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000089', 'Inversiones y Suministros Eléctricos (INSELEC)', 'Valencia', 'Valencia, Estado Carabobo', false, NULL, NULL, NULL, 'Distribución de material eléctrico industrial, breakers, tableros y cables.', 'Distribución de material eléctrico industrial, breakers, tableros y cables.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000090', 'Cocinas y Diseños Domésticos Valencia', 'Valencia', 'C.C. Cristal, Naguanagua/Valencia', true, '+58 241 8990011', NULL, NULL, 'Gabinetes de cocina. Topes de granito residencial.', 'Gabinetes de cocina | Topes de granito residencial', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000091', 'Distribuidora El Pincel de Oro', 'Naguanagua', NULL, false, NULL, NULL, NULL, 'Pinturas en general.', 'Pinturas en general', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000092', 'Sherwin Williams - Tienda San Diego', 'San Diego', 'Municipio San Diego, Estado Carabobo', false, '+58 245 5651111', NULL, NULL, 'Comercialización y distribución de pinturas arquitectónicas, industriales, esmaltes y recubrimientos. Fabricante y comercializador de pinturas arquitectónicas, industriales, automotrices y recubrimientos. Planta de fabricación y centro de distribución de pinturas, esmaltes y recubrimientos arquitectónicos e industriales.', 'Comercialización y distribución de pinturas arquitectónicas, industriales, esmaltes y recubrimientos. | Fabricante y comercializador de pinturas arquitectónicas, industriales, automotrices y recubrimientos. | Planta de fabricación y centro de distribución de pinturas, esmaltes y recubrimientos arquitectónicos e industriales.', NULL, NULL, true, 'Marcado para revisión en archivo fuente', false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresas (id, nombre, municipio, direccion, direccion_precisa, telefono, whatsapp, correo, productos, productos_original, servicios, marca, revisar, nota_revision, contacto_verificado, fuente, tipo_registro)
VALUES ('a0000000-0000-0000-0000-000000000093', 'Tienda Pinturas Montana Naguanagua', 'Naguanagua', 'Av. 190 con Av. Universidad, Naguanagua, Carabobo', true, '+58 241 8683344', '+58 424 4119988', 'naguanagua@tiendasmontana.com', 'Brochas y rodillos. Pinturas caucho profesional. Thinner y solventes.', 'Brochas y rodillos | Pinturas caucho profesional | Thinner y solventes', NULL, NULL, false, NULL, false, 'cadena_construccion_clasificada.xlsx', 'empresa');
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000001', '2.1.4') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000002', '2.1.4') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000003', '2.1.4') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000004', '2.1.4') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000005', '2.1.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000004', '2.1.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000006', '2.1.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000007', '2.1.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000008', '2.1.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000009', '2.1.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000010', '2.1.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000011', '2.1.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000012', '2.1.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000013', '2.1.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000014', '2.1.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000015', '2.1.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000016', '2.2.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000017', '2.2.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000018', '2.2.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000016', '2.2.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000017', '2.2.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000018', '2.2.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000019', '2.3.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000020', '2.3.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000021', '2.3.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000022', '2.3.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000023', '2.3.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000024', '2.3.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000025', '2.3.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000026', '2.3.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000027', '2.3.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000028', '2.3.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000029', '2.4.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000030', '2.4.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000031', '2.4.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000032', '2.4.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000033', '2.4.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000034', '2.4.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000035', '2.4.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000036', '2.5.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000037', '2.5.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000016', '2.5.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000038', '2.5.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000039', '2.5.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000040', '2.6.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000041', '3.1.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000042', '3.1.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000043', '3.1.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000044', '3.1.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000045', '3.1.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000046', '3.1.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000047', '3.1.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000048', '3.1.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000049', '3.1.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000050', '3.1.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000051', '3.1.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000052', '3.1.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000053', '3.1.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000054', '3.1.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000055', '3.1.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000056', '3.1.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000057', '3.1.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000058', '3.2.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000059', '3.2.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000060', '3.2.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000061', '3.2.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000062', '3.2.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000063', '3.2.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000064', '3.2.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000065', '3.2.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000066', '3.2.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000067', '3.2.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000068', '3.2.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000069', '3.2.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000070', '3.2.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000071', '3.2.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000072', '3.2.1') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000073', '3.2.7') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000074', '3.2.7') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000067', '3.2.7') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000075', '3.2.5') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000076', '3.2.5') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000077', '3.2.5') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000072', '3.2.5') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000078', '3.2.5') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000079', '3.2.6') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000080', '3.2.6') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000081', '3.2.6') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000082', '3.2.6') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000083', '3.2.6') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000084', '3.2.6') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000072', '3.2.6') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000058', '3.2.3') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000085', '3.2.3') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000086', '3.2.3') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000075', '3.2.3') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000087', '3.2.3') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000088', '3.2.3') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000089', '3.2.3') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000058', '3.2.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000090', '3.2.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000091', '3.2.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000049', '3.2.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000050', '3.2.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000092', '3.2.2') ON CONFLICT DO NOTHING;
INSERT INTO public.empresa_categorias (empresa_id, categoria_slug) VALUES ('a0000000-0000-0000-0000-000000000093', '3.2.2') ON CONFLICT DO NOTHING;
