-- ==============================================================================
-- DATOS SEMILLA: 10 RAMAS Y 82 SUBCATEGORÍAS (ANEXO A)
-- ==============================================================================
-- Instrucciones:
-- 1. Ve a tu proyecto en Supabase (https://supabase.com/dashboard).
-- 2. Entra en "SQL Editor", crea una "New Query", pega este contenido y pulsa "Run".
-- ==============================================================================

INSERT INTO public.categorias (slug, rama_id, rama_nombre, grupo, nombre, actores, orden)
VALUES
('aridos-grava-arena', 1, 'Extracción y recursos primarios', '1.1 Minería no metálica', 'Áridos (grava, arena)', ARRAY['F']::text[], 1),
('rocas-ornamentales-granito-marmol', 1, 'Extracción y recursos primarios', '1.1 Minería no metálica', 'Rocas ornamentales (granito, mármol)', ARRAY['F']::text[], 2),
('calizas-y-arcillas', 1, 'Extracción y recursos primarios', '1.1 Minería no metálica', 'Calizas y arcillas', ARRAY['F']::text[], 3),
('hierro-bauxita-cobre', 1, 'Extracción y recursos primarios', '1.2 Minería metálica', 'Hierro, bauxita, cobre', ARRAY['F']::text[], 4),
('madera-cruda-sector-forestal', 1, 'Extracción y recursos primarios', '1.3 Otros recursos', 'Madera cruda (sector forestal)', ARRAY['F']::text[], 5),
('agua-industrial', 1, 'Extracción y recursos primarios', '1.3 Otros recursos', 'Agua industrial', ARRAY['S']::text[], 6),
('hidrocarburos-y-derivados', 1, 'Extracción y recursos primarios', '1.3 Otros recursos', 'Hidrocarburos y derivados', ARRAY['F']::text[], 7),
('cemento-gris-blanco-especial-y-clinker', 2, 'Manufactura de materiales', '2.1 Cemento, concreto y prefabricados', 'Cemento (gris, blanco, especial) y clinker', ARRAY['F']::text[], 8),
('concreto-premezclado-y-morteros', 2, 'Manufactura de materiales', '2.1 Cemento, concreto y prefabricados', 'Concreto premezclado y morteros', ARRAY['F']::text[], 9),
('cal-y-yeso', 2, 'Manufactura de materiales', '2.1 Cemento, concreto y prefabricados', 'Cal y yeso', ARRAY['F']::text[], 10),
('bloques-adoquines-y-tuberias-de-concreto', 2, 'Manufactura de materiales', '2.1 Cemento, concreto y prefabricados', 'Bloques, adoquines y tuberías de concreto', ARRAY['F']::text[], 11),
('vigas-pretensadas-y-losacero', 2, 'Manufactura de materiales', '2.1 Cemento, concreto y prefabricados', 'Vigas pretensadas y losacero', ARRAY['F']::text[], 12),
('ladrillos-y-tejas', 2, 'Manufactura de materiales', '2.2 Cerámica, vidrio y sistemas livianos', 'Ladrillos y tejas', ARRAY['F']::text[], 13),
('baldosas-y-porcelanatos', 2, 'Manufactura de materiales', '2.2 Cerámica, vidrio y sistemas livianos', 'Baldosas y porcelanatos', ARRAY['F']::text[], 14),
('piezas-sanitarias', 2, 'Manufactura de materiales', '2.2 Cerámica, vidrio y sistemas livianos', 'Piezas sanitarias', ARRAY['F']::text[], 15),
('vidrio-plano-templado-laminado', 2, 'Manufactura de materiales', '2.2 Cerámica, vidrio y sistemas livianos', 'Vidrio (plano, templado, laminado)', ARRAY['F']::text[], 16),
('drywall-y-fibrocemento', 2, 'Manufactura de materiales', '2.2 Cerámica, vidrio y sistemas livianos', 'Drywall y fibrocemento', ARRAY['F']::text[], 17),
('cabillas-mallas-y-estribos', 2, 'Manufactura de materiales', '2.3 Acero y metalurgia', 'Cabillas, mallas y estribos', ARRAY['F']::text[], 18),
('perfiles-y-planchas-estructurales', 2, 'Manufactura de materiales', '2.3 Acero y metalurgia', 'Perfiles y planchas estructurales', ARRAY['F']::text[], 19),
('laminas-de-techo-galvanizadas-termoacusticas-zinc', 2, 'Manufactura de materiales', '2.3 Acero y metalurgia', 'Láminas de techo (galvanizadas, termoacústicas, zinc)', ARRAY['F']::text[], 20),
('aluminio-para-ventanas', 2, 'Manufactura de materiales', '2.3 Acero y metalurgia', 'Aluminio para ventanas', ARRAY['F']::text[], 21),
('clavos-tornillos-y-anclajes', 2, 'Manufactura de materiales', '2.3 Acero y metalurgia', 'Clavos, tornillos y anclajes', ARRAY['F']::text[], 22),
('tuberias-pvc-cpvc-pead-y-ppr', 2, 'Manufactura de materiales', '2.4 Plásticos y química', 'Tuberías PVC, CPVC, PEAD y PPR', ARRAY['F']::text[], 23),
('tanques-de-polietileno', 2, 'Manufactura de materiales', '2.4 Plásticos y química', 'Tanques de polietileno', ARRAY['F']::text[], 24),
('pinturas-masillas-y-anticorrosivos', 2, 'Manufactura de materiales', '2.4 Plásticos y química', 'Pinturas, masillas y anticorrosivos', ARRAY['F']::text[], 25),
('impermeabilizantes-mantos-asfalticos-y-selladores', 2, 'Manufactura de materiales', '2.4 Plásticos y química', 'Impermeabilizantes, mantos asfálticos y selladores', ARRAY['F']::text[], 26),
('aditivos-pegamentos-y-resinas', 2, 'Manufactura de materiales', '2.4 Plásticos y química', 'Aditivos, pegamentos y resinas', ARRAY['F']::text[], 27),
('cables-baja-media-y-alta-tension', 2, 'Manufactura de materiales', '2.5 Material eléctrico', 'Cables (baja, media y alta tensión)', ARRAY['F']::text[], 28),
('canalizaciones-emt-imc-bandejas', 2, 'Manufactura de materiales', '2.5 Material eléctrico', 'Canalizaciones (EMT, IMC, bandejas)', ARRAY['F']::text[], 29),
('tableros-y-breakers', 2, 'Manufactura de materiales', '2.5 Material eléctrico', 'Tableros y breakers', ARRAY['F']::text[], 30),
('tomacorrientes-apagadores-y-luminarias', 2, 'Manufactura de materiales', '2.5 Material eléctrico', 'Tomacorrientes, apagadores y luminarias', ARRAY['F']::text[], 31),
('madera-para-encofrado-y-andamiaje', 2, 'Manufactura de materiales', '2.6 Madera y derivados', 'Madera para encofrado y andamiaje', ARRAY['F']::text[], 32),
('tableros-plywood-mdf-mdp', 2, 'Manufactura de materiales', '2.6 Madera y derivados', 'Tableros (plywood, MDF, MDP)', ARRAY['F']::text[], 33),
('puertas-marcos-y-carpinteria', 2, 'Manufactura de materiales', '2.6 Madera y derivados', 'Puertas, marcos y carpintería', ARRAY['F']::text[], 34),
('estructuras-modulares-y-paneles-sip', 2, 'Manufactura de materiales', '2.7 Prefabricación y ensamblaje', 'Estructuras modulares y paneles SIP', ARRAY['F']::text[], 35),
('fachadas-y-ventanas-preensambladas', 2, 'Manufactura de materiales', '2.7 Prefabricación y ensamblaje', 'Fachadas y ventanas preensambladas', ARRAY['F']::text[], 36),
('3-1-ferreterias-y-depositos-de-materiales', 3, 'Distribución y comercio de materiales', '3.1 Ferreterías y depósitos de materiales', '3.1 Ferreterías y depósitos de materiales', ARRAY['D']::text[], 37),
('acero', 3, 'Distribución y comercio de materiales', '3.2 Distribuidores especializados', 'Acero', ARRAY['D']::text[], 38),
('material-electrico', 3, 'Distribución y comercio de materiales', '3.2 Distribuidores especializados', 'Material eléctrico', ARRAY['D']::text[], 39),
('sanitarios-y-griferia', 3, 'Distribución y comercio de materiales', '3.2 Distribuidores especializados', 'Sanitarios y grifería', ARRAY['D']::text[], 40),
('pinturas', 3, 'Distribución y comercio de materiales', '3.2 Distribuidores especializados', 'Pinturas', ARRAY['D']::text[], 41),
('acabados', 3, 'Distribución y comercio de materiales', '3.2 Distribuidores especializados', 'Acabados', ARRAY['D']::text[], 42),
('3-3-importadores', 3, 'Distribución y comercio de materiales', '3.3 Importadores', '3.3 Importadores', ARRAY['D']::text[], 43),
('3-4-transporte-y-fletes-de-carga', 3, 'Distribución y comercio de materiales', '3.4 Transporte y fletes de carga', '3.4 Transporte y fletes de carga', ARRAY['A']::text[], 44),
('topografia-y-geotecnia', 4, 'Servicios profesionales y técnicos', '4.1 Estudios previos', 'Topografía y geotecnia', ARRAY['S']::text[], 45),
('estudios-ambientales', 4, 'Servicios profesionales y técnicos', '4.1 Estudios previos', 'Estudios ambientales', ARRAY['S']::text[], 46),
('arquitectura-y-bim', 4, 'Servicios profesionales y técnicos', '4.2 Diseño e ingeniería', 'Arquitectura y BIM', ARRAY['S']::text[], 47),
('calculo-estructural', 4, 'Servicios profesionales y técnicos', '4.2 Diseño e ingeniería', 'Cálculo estructural', ARRAY['S']::text[], 48),
('proyectos-mep', 4, 'Servicios profesionales y técnicos', '4.2 Diseño e ingeniería', 'Proyectos MEP', ARRAY['S']::text[], 49),
('permisos-y-licencias', 4, 'Servicios profesionales y técnicos', '4.3 Gestión y control', 'Permisos y licencias', ARRAY['S']::text[], 50),
('gerencia-e-inspeccion-de-obra', 4, 'Servicios profesionales y técnicos', '4.3 Gestión y control', 'Gerencia e inspección de obra', ARRAY['S']::text[], 51),
('laboratorios-de-control-de-calidad', 4, 'Servicios profesionales y técnicos', '4.3 Gestión y control', 'Laboratorios de control de calidad', ARRAY['S']::text[], 52),
('seguridad-industrial-y-dotacion-epp', 4, 'Servicios profesionales y técnicos', '4.3 Gestión y control', 'Seguridad industrial y dotación (EPP)', ARRAY['S']::text[], 53),
('edificacion-residencial-y-no-residencial', 5, 'Ejecución de obra', '5.1 Tipos de contratista', 'Edificación residencial y no residencial', ARRAY['C']::text[], 54),
('obras-civiles-e-infraestructura', 5, 'Ejecución de obra', '5.1 Tipos de contratista', 'Obras civiles e infraestructura', ARRAY['C']::text[], 55),
('subcontratistas-por-especialidad', 5, 'Ejecución de obra', '5.1 Tipos de contratista', 'Subcontratistas por especialidad', ARRAY['C']::text[], 56),
('preliminares-y-cimentacion-movimiento-de-tierras-pilotes-zap', 5, 'Ejecución de obra', '5.2 Etapas de obra', 'Preliminares y cimentación (movimiento de tierras, pilotes, zapatas)', ARRAY['C']::text[], 57),
('obra-negra-estructura-columnas-vigas-y-losas', 5, 'Ejecución de obra', '5.2 Etapas de obra', 'Obra negra: estructura, columnas, vigas y losas', ARRAY['C']::text[], 58),
('obra-gris-instalaciones-mep-hvac-domotica-y-cableado', 5, 'Ejecución de obra', '5.2 Etapas de obra', 'Obra gris: instalaciones MEP, HVAC, domótica y cableado', ARRAY['C']::text[], 59),
('obra-blanca-pisos-estucos-pintura-carpinteria-y-paisajismo', 5, 'Ejecución de obra', '5.2 Etapas de obra', 'Obra blanca: pisos, estucos, pintura, carpintería y paisajismo', ARRAY['C']::text[], 60),
('gruas-excavadoras-mezcladoras', 6, 'Equipos, maquinaria y suministros especiales', '6.1 Maquinaria pesada', 'Grúas, excavadoras, mezcladoras', ARRAY['F','A']::text[], 61),
('6-2-andamios-y-encofrados', 6, 'Equipos, maquinaria y suministros especiales', '6.2 Andamios y encofrados', '6.2 Andamios y encofrados', ARRAY['F','A']::text[], 62),
('ascensores-y-escaleras-mecanicas', 6, 'Equipos, maquinaria y suministros especiales', '6.3 Equipos de edificación', 'Ascensores y escaleras mecánicas', ARRAY['F','S']::text[], 63),
('hvac', 6, 'Equipos, maquinaria y suministros especiales', '6.3 Equipos de edificación', 'HVAC', ARRAY['F','S']::text[], 64),
('bombas-e-hidroneumaticos', 6, 'Equipos, maquinaria y suministros especiales', '6.3 Equipos de edificación', 'Bombas e hidroneumáticos', ARRAY['F','S']::text[], 65),
('transformadores', 6, 'Equipos, maquinaria y suministros especiales', '6.3 Equipos de edificación', 'Transformadores', ARRAY['F','S']::text[], 66),
('7-1-banca-fiducias-y-creditos-puente', 7, 'Financiamiento y comercialización', '7.1 Banca, fiducias y créditos puente', '7.1 Banca, fiducias y créditos puente', ARRAY['S']::text[], 67),
('7-2-seguros-todo-riesgo', 7, 'Financiamiento y comercialización', '7.2 Seguros (todo riesgo)', '7.2 Seguros (todo riesgo)', ARRAY['S']::text[], 68),
('7-3-inmobiliarias-corretaje-y-avaluos', 7, 'Financiamiento y comercialización', '7.3 Inmobiliarias, corretaje y avalúos', '7.3 Inmobiliarias, corretaje y avalúos', ARRAY['S']::text[], 69),
('7-4-notarias-y-registros', 7, 'Financiamiento y comercialización', '7.4 Notarías y registros', '7.4 Notarías y registros', ARRAY['S']::text[], 70),
('8-1-facility-management-y-mantenimiento', 8, 'Operación y fin de ciclo', '8.1 Facility management y mantenimiento', '8.1 Facility management y mantenimiento', ARRAY['S']::text[], 71),
('8-2-demolicion-tecnica', 8, 'Operación y fin de ciclo', '8.2 Demolición técnica', '8.2 Demolición técnica', ARRAY['C']::text[], 72),
('8-3-reciclaje-de-residuos-rcd-retorna-a-la-rama-2', 8, 'Operación y fin de ciclo', '8.3 Reciclaje de residuos (RCD), retorna a la rama 2', '8.3 Reciclaje de residuos (RCD), retorna a la rama 2', ARRAY['F','S']::text[], 73),
('familias', 9, 'Demanda final', 'Quién compra', 'Familias', '{}'::text[], 74),
('sector-publico-gobernacion-alcaldias-y-ministerios', 9, 'Demanda final', 'Quién compra', 'Sector público: gobernación, alcaldías y ministerios', '{}'::text[], 75),
('empresas-privadas-e-industria', 9, 'Demanda final', 'Quién compra', 'Empresas privadas e industria', '{}'::text[], 76),
('valencia', 10, 'Referencia territorial: Carabobo', 'Municipios y zonas', 'Valencia', '{}'::text[], 77),
('los-guayos', 10, 'Referencia territorial: Carabobo', 'Municipios y zonas', 'Los Guayos', '{}'::text[], 78),
('guacara', 10, 'Referencia territorial: Carabobo', 'Municipios y zonas', 'Guacara', '{}'::text[], 79),
('san-diego', 10, 'Referencia territorial: Carabobo', 'Municipios y zonas', 'San Diego', '{}'::text[], 80),
('puerto-cabello', 10, 'Referencia territorial: Carabobo', 'Municipios y zonas', 'Puerto Cabello', '{}'::text[], 81),
('otros-municipios', 10, 'Referencia territorial: Carabobo', 'Municipios y zonas', 'Otros municipios', '{}'::text[], 82)
ON CONFLICT (slug) DO UPDATE SET
  rama_id = EXCLUDED.rama_id,
  rama_nombre = EXCLUDED.rama_nombre,
  grupo = EXCLUDED.grupo,
  nombre = EXCLUDED.nombre,
  actores = EXCLUDED.actores,
  orden = EXCLUDED.orden;
